package random

// CountryDetails struct holds the ISO 3166-1 alpha-2 code, ISO 3166-1 alpha-3 code, and Internet country code top-level domain (ccTLD) for a country.
type Country struct {
	Code2 string // ISO 3166-1 alpha-2 code
	Code3 string // ISO 3166-1 alpha-3 code
	CCTLD string // Internet country code top-level domain
}

// Countries is a map of country names to their ISO 3166-1 alpha-2 code, ISO 3166-1 alpha-3 code, and ccTLD.
var Countries = map[string]Country{
	"Afghanistan":                      {Code2: "AF", Code3: "AFG", CCTLD: "af"},
	"Albania":                          {Code2: "AL", Code3: "ALB", CCTLD: "al"},
	"Algeria":                          {Code2: "DZ", Code3: "DZA", CCTLD: "dz"},
	"Andorra":                          {Code2: "AD", Code3: "AND", CCTLD: "ad"},
	"Angola":                           {Code2: "AO", Code3: "AGO", CCTLD: "ao"},
	"Antigua and Barbuda":              {Code2: "AG", Code3: "ATG", CCTLD: "ag"},
	"Argentina":                        {Code2: "AR", Code3: "ARG", CCTLD: "ar"},
	"Armenia":                          {Code2: "AM", Code3: "ARM", CCTLD: "am"},
	"Australia":                        {Code2: "AU", Code3: "AUS", CCTLD: "au"},
	"Austria":                          {Code2: "AT", Code3: "AUT", CCTLD: "at"},
	"Azerbaijan":                       {Code2: "AZ", Code3: "AZE", CCTLD: "az"},
	"Bahamas":                          {Code2: "BS", Code3: "BHS", CCTLD: "bs"},
	"Bahrain":                          {Code2: "BH", Code3: "BHR", CCTLD: "bh"},
	"Bangladesh":                       {Code2: "BD", Code3: "BGD", CCTLD: "bd"},
	"Barbados":                         {Code2: "BB", Code3: "BRB", CCTLD: "bb"},
	"Belarus":                          {Code2: "BY", Code3: "BLR", CCTLD: "by"},
	"Belgium":                          {Code2: "BE", Code3: "BEL", CCTLD: "be"},
	"Belize":                           {Code2: "BZ", Code3: "BLZ", CCTLD: "bz"},
	"Benin":                            {Code2: "BJ", Code3: "BEN", CCTLD: "bj"},
	"Bhutan":                           {Code2: "BT", Code3: "BTN", CCTLD: "bt"},
	"Bolivia":                          {Code2: "BO", Code3: "BOL", CCTLD: "bo"},
	"Bosnia and Herzegovina":           {Code2: "BA", Code3: "BIH", CCTLD: "ba"},
	"Botswana":                         {Code2: "BW", Code3: "BWA", CCTLD: "bw"},
	"Brazil":                           {Code2: "BR", Code3: "BRA", CCTLD: "br"},
	"Brunei":                           {Code2: "BN", Code3: "BRN", CCTLD: "bn"},
	"Bulgaria":                         {Code2: "BG", Code3: "BGR", CCTLD: "bg"},
	"Burkina Faso":                     {Code2: "BF", Code3: "BFA", CCTLD: "bf"},
	"Burundi":                          {Code2: "BI", Code3: "BDI", CCTLD: "bi"},
	"Cabo Verde":                       {Code2: "CV", Code3: "CPV", CCTLD: "cv"},
	"Cambodia":                         {Code2: "KH", Code3: "KHM", CCTLD: "kh"},
	"Cameroon":                         {Code2: "CM", Code3: "CMR", CCTLD: "cm"},
	"Canada":                           {Code2: "CA", Code3: "CAN", CCTLD: "ca"},
	"Central African Republic":         {Code2: "CF", Code3: "CAF", CCTLD: "cf"},
	"Chad":                             {Code2: "TD", Code3: "TCD", CCTLD: "td"},
	"Chile":                            {Code2: "CL", Code3: "CHL", CCTLD: "cl"},
	"China":                            {Code2: "CN", Code3: "CHN", CCTLD: "cn"},
	"Colombia":                         {Code2: "CO", Code3: "COL", CCTLD: "co"},
	"Comoros":                          {Code2: "KM", Code3: "COM", CCTLD: "km"},
	"Congo":                            {Code2: "CG", Code3: "COG", CCTLD: "cg"}, // Congo-Brazzaville
	"Democratic Republic of Congo":     {Code2: "CD", Code3: "COD", CCTLD: "cd"},
	"Costa Rica":                       {Code2: "CR", Code3: "CRI", CCTLD: "cr"},
	"Croatia":                          {Code2: "HR", Code3: "HRV", CCTLD: "hr"},
	"Cuba":                             {Code2: "CU", Code3: "CUB", CCTLD: "cu"},
	"Cyprus":                           {Code2: "CY", Code3: "CYP", CCTLD: "cy"},
	"Czechia":                          {Code2: "CZ", Code3: "CZE", CCTLD: "cz"}, // Czech Republic
	"Denmark":                          {Code2: "DK", Code3: "DNK", CCTLD: "dk"},
	"Djibouti":                         {Code2: "DJ", Code3: "DJI", CCTLD: "dj"},
	"Dominica":                         {Code2: "DM", Code3: "DMA", CCTLD: "dm"},
	"Dominican Republic":               {Code2: "DO", Code3: "DOM", CCTLD: "do"},
	"Ecuador":                          {Code2: "EC", Code3: "ECU", CCTLD: "ec"},
	"Egypt":                            {Code2: "EG", Code3: "EGY", CCTLD: "eg"},
	"El Salvador":                      {Code2: "SV", Code3: "SLV", CCTLD: "sv"},
	"Equatorial Guinea":                {Code2: "GQ", Code3: "GNQ", CCTLD: "gq"},
	"Eritrea":                          {Code2: "ER", Code3: "ERI", CCTLD: "er"},
	"Estonia":                          {Code2: "EE", Code3: "EST", CCTLD: "ee"},
	"Eswatini":                         {Code2: "SZ", Code3: "SWZ", CCTLD: "sz"},
	"Ethiopia":                         {Code2: "ET", Code3: "ETH", CCTLD: "et"},
	"Fiji":                             {Code2: "FJ", Code3: "FJI", CCTLD: "fj"},
	"Finland":                          {Code2: "FI", Code3: "FIN", CCTLD: "fi"},
	"France":                           {Code2: "FR", Code3: "FRA", CCTLD: "fr"},
	"Gabon":                            {Code2: "GA", Code3: "GAB", CCTLD: "ga"},
	"Gambia":                           {Code2: "GM", Code3: "GMB", CCTLD: "gm"},
	"Georgia":                          {Code2: "GE", Code3: "GEO", CCTLD: "ge"},
	"Germany":                          {Code2: "DE", Code3: "DEU", CCTLD: "de"},
	"Ghana":                            {Code2: "GH", Code3: "GHA", CCTLD: "gh"},
	"Greece":                           {Code2: "GR", Code3: "GRC", CCTLD: "gr"},
	"Grenada":                          {Code2: "GD", Code3: "GRD", CCTLD: "gd"},
	"Guatemala":                        {Code2: "GT", Code3: "GTM", CCTLD: "gt"},
	"Guinea":                           {Code2: "GN", Code3: "GIN", CCTLD: "gn"},
	"Guinea-Bissau":                    {Code2: "GW", Code3: "GNB", CCTLD: "gw"},
	"Guyana":                           {Code2: "GY", Code3: "GUY", CCTLD: "gy"},
	"Haiti":                            {Code2: "HT", Code3: "HTI", CCTLD: "ht"},
	"Honduras":                         {Code2: "HN", Code3: "HND", CCTLD: "hn"},
	"Hungary":                          {Code2: "HU", Code3: "HUN", CCTLD: "hu"},
	"Iceland":                          {Code2: "IS", Code3: "ISL", CCTLD: "is"},
	"India":                            {Code2: "IN", Code3: "IND", CCTLD: "in"},
	"Indonesia":                        {Code2: "ID", Code3: "IDN", CCTLD: "id"},
	"Iran":                             {Code2: "IR", Code3: "IRN", CCTLD: "ir"},
	"Iraq":                             {Code2: "IQ", Code3: "IRQ", CCTLD: "iq"},
	"Ireland":                          {Code2: "IE", Code3: "IRL", CCTLD: "ie"},
	"Israel":                           {Code2: "IL", Code3: "ISR", CCTLD: "il"},
	"Italy":                            {Code2: "IT", Code3: "ITA", CCTLD: "it"},
	"Jamaica":                          {Code2: "JM", Code3: "JAM", CCTLD: "jm"},
	"Japan":                            {Code2: "JP", Code3: "JPN", CCTLD: "jp"},
	"Jordan":                           {Code2: "JO", Code3: "JOR", CCTLD: "jo"},
	"Kazakhstan":                       {Code2: "KZ", Code3: "KAZ", CCTLD: "kz"},
	"Kenya":                            {Code2: "KE", Code3: "KEN", CCTLD: "ke"},
	"Kiribati":                         {Code2: "KI", Code3: "KIR", CCTLD: "ki"},
	"North Korea":                      {Code2: "KP", Code3: "PRK", CCTLD: "kp"}, // North Korea
	"South Korea":                      {Code2: "KR", Code3: "KOR", CCTLD: "kr"}, // South Korea
	"Kuwait":                           {Code2: "KW", Code3: "KWT", CCTLD: "kw"},
	"Kyrgyzstan":                       {Code2: "KG", Code3: "KGZ", CCTLD: "kg"},
	"Laos":                             {Code2: "LA", Code3: "LAO", CCTLD: "la"},
	"Latvia":                           {Code2: "LV", Code3: "LVA", CCTLD: "lv"},
	"Lebanon":                          {Code2: "LB", Code3: "LBN", CCTLD: "lb"},
	"Lesotho":                          {Code2: "LS", Code3: "LSO", CCTLD: "ls"},
	"Liberia":                          {Code2: "LR", Code3: "LBR", CCTLD: "lr"},
	"Libya":                            {Code2: "LY", Code3: "LBY", CCTLD: "ly"},
	"Liechtenstein":                    {Code2: "LI", Code3: "LIE", CCTLD: "li"},
	"Lithuania":                        {Code2: "LT", Code3: "LTU", CCTLD: "lt"},
	"Luxembourg":                       {Code2: "LU", Code3: "LUX", CCTLD: "lu"},
	"Madagascar":                       {Code2: "MG", Code3: "MDG", CCTLD: "mg"},
	"Malawi":                           {Code2: "MW", Code3: "MWI", CCTLD: "mw"},
	"Malaysia":                         {Code2: "MY", Code3: "MYS", CCTLD: "my"},
	"Maldives":                         {Code2: "MV", Code3: "MDV", CCTLD: "mv"},
	"Mali":                             {Code2: "ML", Code3: "MLI", CCTLD: "ml"},
	"Malta":                            {Code2: "MT", Code3: "MLT", CCTLD: "mt"},
	"Marshall Islands":                 {Code2: "MH", Code3: "MHL", CCTLD: "mh"},
	"Mauritania":                       {Code2: "MR", Code3: "MRT", CCTLD: "mr"},
	"Mauritius":                        {Code2: "MU", Code3: "MUS", CCTLD: "mu"},
	"Mexico":                           {Code2: "MX", Code3: "MEX", CCTLD: "mx"},
	"Micronesia":                       {Code2: "FM", Code3: "FSM", CCTLD: "fm"},
	"Moldova":                          {Code2: "MD", Code3: "MDA", CCTLD: "md"},
	"Monaco":                           {Code2: "MC", Code3: "MCO", CCTLD: "mc"},
	"Mongolia":                         {Code2: "MN", Code3: "MNG", CCTLD: "mn"},
	"Montenegro":                       {Code2: "ME", Code3: "MNE", CCTLD: "me"},
	"Morocco":                          {Code2: "MA", Code3: "MAR", CCTLD: "ma"},
	"Mozambique":                       {Code2: "MZ", Code3: "MOZ", CCTLD: "mz"},
	"Myanmar":                          {Code2: "MM", Code3: "MMR", CCTLD: "mm"}, // formerly Burma
	"Namibia":                          {Code2: "NA", Code3: "NAM", CCTLD: "na"},
	"Nauru":                            {Code2: "NR", Code3: "NRU", CCTLD: "nr"},
	"Nepal":                            {Code2: "NP", Code3: "NPL", CCTLD: "np"},
	"Netherlands":                      {Code2: "NL", Code3: "NLD", CCTLD: "nl"},
	"New Zealand":                      {Code2: "NZ", Code3: "NZL", CCTLD: "nz"},
	"Nicaragua":                        {Code2: "NI", Code3: "NIC", CCTLD: "ni"},
	"Niger":                            {Code2: "NE", Code3: "NER", CCTLD: "ne"},
	"Nigeria":                          {Code2: "NG", Code3: "NGA", CCTLD: "ng"},
	"North Macedonia":                  {Code2: "MK", Code3: "MKD", CCTLD: "mk"},
	"Norway":                           {Code2: "NO", Code3: "NOR", CCTLD: "no"},
	"Oman":                             {Code2: "OM", Code3: "OMN", CCTLD: "om"},
	"Pakistan":                         {Code2: "PK", Code3: "PAK", CCTLD: "pk"},
	"Palau":                            {Code2: "PW", Code3: "PLW", CCTLD: "pw"},
	"Palestine State":                  {Code2: "PS", Code3: "PSE", CCTLD: "ps"},
	"Panama":                           {Code2: "PA", Code3: "PAN", CCTLD: "pa"},
	"Papua New Guinea":                 {Code2: "PG", Code3: "PNG", CCTLD: "pg"},
	"Paraguay":                         {Code2: "PY", Code3: "PRY", CCTLD: "py"},
	"Peru":                             {Code2: "PE", Code3: "PER", CCTLD: "pe"},
	"Philippines":                      {Code2: "PH", Code3: "PHL", CCTLD: "ph"},
	"Poland":                           {Code2: "PL", Code3: "POL", CCTLD: "pl"},
	"Portugal":                         {Code2: "PT", Code3: "PRT", CCTLD: "pt"},
	"Qatar":                            {Code2: "QA", Code3: "QAT", CCTLD: "qa"},
	"Romania":                          {Code2: "RO", Code3: "ROU", CCTLD: "ro"},
	"Russia":                           {Code2: "RU", Code3: "RUS", CCTLD: "ru"},
	"Rwanda":                           {Code2: "RW", Code3: "RWA", CCTLD: "rw"},
	"Saint Kitts and Nevis":            {Code2: "KN", Code3: "KNA", CCTLD: "kn"},
	"Saint Lucia":                      {Code2: "LC", Code3: "LCA", CCTLD: "lc"},
	"Saint Vincent and the Grenadines": {Code2: "VC", Code3: "VCT", CCTLD: "vc"},
	"Samoa":                            {Code2: "WS", Code3: "WSM", CCTLD: "ws"},
	"San Marino":                       {Code2: "SM", Code3: "SMR", CCTLD: "sm"},
	"Sao Tome and Principe":            {Code2: "ST", Code3: "STP", CCTLD: "st"},
	"Saudi Arabia":                     {Code2: "SA", Code3: "SAU", CCTLD: "sa"},
	"Senegal":                          {Code2: "SN", Code3: "SEN", CCTLD: "sn"},
	"Serbia":                           {Code2: "RS", Code3: "SRB", CCTLD: "rs"},
	"Seychelles":                       {Code2: "SC", Code3: "SYC", CCTLD: "sc"},
	"Sierra Leone":                     {Code2: "SL", Code3: "SLE", CCTLD: "sl"},
	"Singapore":                        {Code2: "SG", Code3: "SGP", CCTLD: "sg"},
	"Slovakia":                         {Code2: "SK", Code3: "SVK", CCTLD: "sk"},
	"Slovenia":                         {Code2: "SI", Code3: "SVN", CCTLD: "si"},
	"Solomon Islands":                  {Code2: "SB", Code3: "SLB", CCTLD: "sb"},
	"Somalia":                          {Code2: "SO", Code3: "SOM", CCTLD: "so"},
	"South Africa":                     {Code2: "ZA", Code3: "ZAF", CCTLD: "za"},
	"South Sudan":                      {Code2: "SS", Code3: "SSD", CCTLD: "ss"},
	"Spain":                            {Code2: "ES", Code3: "ESP", CCTLD: "es"},
	"Sri Lanka":                        {Code2: "LK", Code3: "LKA", CCTLD: "lk"},
	"Sudan":                            {Code2: "SD", Code3: "SDN", CCTLD: "sd"},
	"Suriname":                         {Code2: "SR", Code3: "SUR", CCTLD: "sr"},
	"Sweden":                           {Code2: "SE", Code3: "SWE", CCTLD: "se"},
	"Switzerland":                      {Code2: "CH", Code3: "CHE", CCTLD: "ch"},
	"Syria":                            {Code2: "SY", Code3: "SYR", CCTLD: "sy"},
	"Taiwan":                           {Code2: "TW", Code3: "TWN", CCTLD: "tw"},
	"Tajikistan":                       {Code2: "TJ", Code3: "TJK", CCTLD: "tj"},
	"Tanzania":                         {Code2: "TZ", Code3: "TZA", CCTLD: "tz"},
	"Thailand":                         {Code2: "TH", Code3: "THA", CCTLD: "th"},
	"Timor-Leste":                      {Code2: "TL", Code3: "TLS", CCTLD: "tl"},
	"Togo":                             {Code2: "TG", Code3: "TGO", CCTLD: "tg"},
	"Tonga":                            {Code2: "TO", Code3: "TON", CCTLD: "to"},
	"Trinidad and Tobago":              {Code2: "TT", Code3: "TTO", CCTLD: "tt"},
	"Tunisia":                          {Code2: "TN", Code3: "TUN", CCTLD: "tn"},
	"Turkey":                           {Code2: "TR", Code3: "TUR", CCTLD: "tr"},
	"Turkmenistan":                     {Code2: "TM", Code3: "TKM", CCTLD: "tm"},
	"Tuvalu":                           {Code2: "TV", Code3: "TUV", CCTLD: "tv"},
	"Uganda":                           {Code2: "UG", Code3: "UGA", CCTLD: "ug"},
	"Ukraine":                          {Code2: "UA", Code3: "UKR", CCTLD: "ua"},
	"United Arab Emirates":             {Code2: "AE", Code3: "ARE", CCTLD: "ae"},
	"United Kingdom":                   {Code2: "GB", Code3: "GBR", CCTLD: "uk"},
	"United States of America":         {Code2: "US", Code3: "USA", CCTLD: "us"},
	"Uruguay":                          {Code2: "UY", Code3: "URY", CCTLD: "uy"},
	"Uzbekistan":                       {Code2: "UZ", Code3: "UZB", CCTLD: "uz"},
	"Vanuatu":                          {Code2: "VU", Code3: "VUT", CCTLD: "vu"},
	"Holy See":                         {Code2: "VA", Code3: "VAT", CCTLD: "va"}, // Vatican City
	"Venezuela":                        {Code2: "VE", Code3: "VEN", CCTLD: "ve"},
	"Viet Nam":                         {Code2: "VN", Code3: "VNM", CCTLD: "vn"},
	"Western Sahara":                   {Code2: "EH", Code3: "ESH", CCTLD: "eh"},
	"Yemen":                            {Code2: "YE", Code3: "YEM", CCTLD: "ye"},
	"Zambia":                           {Code2: "ZM", Code3: "ZMB", CCTLD: "zm"},
	"Zimbabwe":                         {Code2: "ZW", Code3: "ZWE", CCTLD: "zw"},
}
